import { useState } from "react";

import Head from "next/head";
import Image from "next/image";
// import Header from "../components/shared/Header2";
import Header from "../components/shared/Header";
import Main from "../components/general/Main";
import Footer from "../components/shared/Footer";
import GoToTop from "../components/general/GoToTop";
import SignUpModal from "../components/my-additions/SignUpModal";
// import styles from "../styles/Home.module.css";

export default function Home() {
  const [showSignUp, setShowSignUp] = useState(false);

  // const handleClick = () => {

  // }

  return (
    <div>
      <Head>
        <title>Eduspace - Education landing page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header setShowSignUp={setShowSignUp} />
      {showSignUp && <SignUpModal setShowSignUp={setShowSignUp} />}

      <Main />
      <Footer />
      <GoToTop />

      {/* <main className={styles.main}></main>

      <footer className={styles.footer}></footer> */}
    </div>
  );
}
